package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object BoltTech : ShadcnStyles {
    override val background: Color = Color(0xFFFFFFFF)
    override val foreground: Color = Color(0xFF312E81)
    override val card: Color = Color(0xFFFFFFFF)
    override val cardForeground: Color = Color(0xFF312E81)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF312E81)
    override val primary: Color = Color(0xFF8B5CF6)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFF3F0FF)
    override val secondaryForeground: Color = Color(0xFF4338CA)
    override val muted: Color = Color(0xFFF5F3FF)
    override val mutedForeground: Color = Color(0xFF7C3AED)
    override val accent: Color = Color(0xFFDBEAFE)
    override val accentForeground: Color = Color(0xFF1E40AF)
    override val destructive: Color = Color(0xFFEF4444)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFE0E7FF)
    override val input: Color = Color(0xFFE0E7FF)
    override val ring: Color = Color(0xFF8B5CF6)
    override val chart1: Color = Color(0xFF8B5CF6)
    override val chart2: Color = Color(0xFF7C3AED)
    override val chart3: Color = Color(0xFF6D28D9)
    override val chart4: Color = Color(0xFF5B21B6)
    override val chart5: Color = Color(0xFF4C1D95)
    override val sidebar: Color = Color(0xFFF5F3FF)
    override val sidebarForeground: Color = Color(0xFF312E81)
    override val sidebarPrimary: Color = Color(0xFF8B5CF6)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFFDBEAFE)
    override val sidebarAccentForeground: Color = Color(0xFF1E40AF)
    override val sidebarBorder: Color = Color(0xFFE0E7FF)
    override val sidebarRing: Color = Color(0xFF8B5CF6)
    override val snackbar: Color = Color(0xFFFFFFFF)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object BoltTechDark : ShadcnStyles {
    override val background: Color = Color(0xFF0F172A)
    override val foreground: Color = Color(0xFFE0E7FF)
    override val card: Color = Color(0xFF1E1B4B)
    override val cardForeground: Color = Color(0xFFE0E7FF)
    override val popover: Color = Color(0xFF1E1B4B)
    override val popoverForeground: Color = Color(0xFFE0E7FF)
    override val primary: Color = Color(0xFF8B5CF6)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFF1E1B4B)
    override val secondaryForeground: Color = Color(0xFFE0E7FF)
    override val muted: Color = Color(0xFF171447)
    override val mutedForeground: Color = Color(0xFFC4B5FD)
    override val accent: Color = Color(0xFF4338CA)
    override val accentForeground: Color = Color(0xFFE0E7FF)
    override val destructive: Color = Color(0xFFEF4444)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFF2E1065)
    override val input: Color = Color(0xFF2E1065)
    override val ring: Color = Color(0xFF8B5CF6)
    override val chart1: Color = Color(0xFFA78BFA)
    override val chart2: Color = Color(0xFF8B5CF6)
    override val chart3: Color = Color(0xFF7C3AED)
    override val chart4: Color = Color(0xFF6D28D9)
    override val chart5: Color = Color(0xFF5B21B6)
    override val sidebar: Color = Color(0xFF0F172A)
    override val sidebarForeground: Color = Color(0xFFE0E7FF)
    override val sidebarPrimary: Color = Color(0xFF8B5CF6)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFF4338CA)
    override val sidebarAccentForeground: Color = Color(0xFFE0E7FF)
    override val sidebarBorder: Color = Color(0xFF2E1065)
    override val sidebarRing: Color = Color(0xFF8B5CF6)
    override val snackbar: Color = Color(0xFF0F172A)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 2.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}