package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object Bubblegum : ShadcnStyles {
    override val background: Color = Color(0xFFF6E6EE)
    override val foreground: Color = Color(0xFF5B5B5B)
    override val card: Color = Color(0xFFFDEDC9)
    override val cardForeground: Color = Color(0xFF5B5B5B)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF5B5B5B)
    override val primary: Color = Color(0xFFD04F99)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFF8ACFD1)
    override val secondaryForeground: Color = Color(0xFF333333)
    override val muted: Color = Color(0xFFB2E1EB)
    override val mutedForeground: Color = Color(0xFF7A7A7A)
    override val accent: Color = Color(0xFFFBE2A7)
    override val accentForeground: Color = Color(0xFF333333)
    override val destructive: Color = Color(0xFFF96F70)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFD04F99)
    override val input: Color = Color(0xFFE4E4E4)
    override val ring: Color = Color(0xFFE670AB)
    override val chart1: Color = Color(0xFFE670AB)
    override val chart2: Color = Color(0xFF84D2E2)
    override val chart3: Color = Color(0xFFFBE2A7)
    override val chart4: Color = Color(0xFFF3A0CA)
    override val chart5: Color = Color(0xFFD7488E)
    override val sidebar: Color = Color(0xFFF8D8EA)
    override val sidebarForeground: Color = Color(0xFF333333)
    override val sidebarPrimary: Color = Color(0xFFEC4899)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFFF9A8D4)
    override val sidebarAccentForeground: Color = Color(0xFF333333)
    override val sidebarBorder: Color = Color(0xFFF3E8FF)
    override val sidebarRing: Color = Color(0xFFEC4899)
    override val snackbar: Color = Color(0xFFF6E6EE)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 6.dp,
            offsetY = 6.dp,
            blurRadius = 0.dp,
            spread = 4.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object BubblegumDark : ShadcnStyles {
    override val background: Color = Color(0xFF12242E)
    override val foreground: Color = Color(0xFFF3E3EA)
    override val card: Color = Color(0xFF1C2E38)
    override val cardForeground: Color = Color(0xFFF3E3EA)
    override val popover: Color = Color(0xFF1C2E38)
    override val popoverForeground: Color = Color(0xFFF3E3EA)
    override val primary: Color = Color(0xFFFBE2A7)
    override val primaryForeground: Color = Color(0xFF12242E)
    override val secondary: Color = Color(0xFFE4A2B1)
    override val secondaryForeground: Color = Color(0xFF12242E)
    override val muted: Color = Color(0xFF24272B)
    override val mutedForeground: Color = Color(0xFFE4A2B1)
    override val accent: Color = Color(0xFFC67B96)
    override val accentForeground: Color = Color(0xFFF3E3EA)
    override val destructive: Color = Color(0xFFE35EA4)
    override val destructiveForeground: Color = Color(0xFF12242E)
    override val border: Color = Color(0xFF324859)
    override val input: Color = Color(0xFF20333D)
    override val ring: Color = Color(0xFF50AFB6)
    override val chart1: Color = Color(0xFF50AFB6)
    override val chart2: Color = Color(0xFFE4A2B1)
    override val chart3: Color = Color(0xFFC67B96)
    override val chart4: Color = Color(0xFF175C6C)
    override val chart5: Color = Color(0xFF24272B)
    override val sidebar: Color = Color(0xFF101F28)
    override val sidebarForeground: Color = Color(0xFFF3F4F6)
    override val sidebarPrimary: Color = Color(0xFFEC4899)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFFF9A8D4)
    override val sidebarAccentForeground: Color = Color(0xFF1F2937)
    override val sidebarBorder: Color = Color(0xFF374151)
    override val sidebarRing: Color = Color(0xFFEC4899)
    override val snackbar: Color = Color(0xFF12242E)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 3.dp,
            offsetY = 3.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}