package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object Caffeine : ShadcnStyles {
    override val background: Color = Color(0xFFF9F9F9)
    override val foreground: Color = Color(0xFF202020)
    override val card: Color = Color(0xFFFCFCFC)
    override val cardForeground: Color = Color(0xFF202020)
    override val popover: Color = Color(0xFFFCFCFC)
    override val popoverForeground: Color = Color(0xFF202020)
    override val primary: Color = Color(0xFF644A40)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFFFDFB5)
    override val secondaryForeground: Color = Color(0xFF582D1D)
    override val muted: Color = Color(0xFFEFEFEF)
    override val mutedForeground: Color = Color(0xFF646464)
    override val accent: Color = Color(0xFFE8E8E8)
    override val accentForeground: Color = Color(0xFF202020)
    override val destructive: Color = Color(0xFFE54D2E)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFD8D8D8)
    override val input: Color = Color(0xFFD8D8D8)
    override val ring: Color = Color(0xFF644A40)
    override val chart1: Color = Color(0xFF644A40)
    override val chart2: Color = Color(0xFFFFDFB5)
    override val chart3: Color = Color(0xFFE8E8E8)
    override val chart4: Color = Color(0xFFFFE6C4)
    override val chart5: Color = Color(0xFF66493E)
    override val sidebar: Color = Color(0xFFFBFBFB)
    override val sidebarForeground: Color = Color(0xFF252525)
    override val sidebarPrimary: Color = Color(0xFF343434)
    override val sidebarPrimaryForeground: Color = Color(0xFFFBFBFB)
    override val sidebarAccent: Color = Color(0xFFF7F7F7)
    override val sidebarAccentForeground: Color = Color(0xFF343434)
    override val sidebarBorder: Color = Color(0xFFEBEBEB)
    override val sidebarRing: Color = Color(0xFFB5B5B5)
    override val snackbar: Color = Color(0xFFF9F9F9)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object CaffeineDark : ShadcnStyles {
    override val background: Color = Color(0xFF111111)
    override val foreground: Color = Color(0xFFEEEEEE)
    override val card: Color = Color(0xFF191919)
    override val cardForeground: Color = Color(0xFFEEEEEE)
    override val popover: Color = Color(0xFF191919)
    override val popoverForeground: Color = Color(0xFFEEEEEE)
    override val primary: Color = Color(0xFFFFE0C2)
    override val primaryForeground: Color = Color(0xFF081A1B)
    override val secondary: Color = Color(0xFF393028)
    override val secondaryForeground: Color = Color(0xFFFFE0C2)
    override val muted: Color = Color(0xFF222222)
    override val mutedForeground: Color = Color(0xFFB4B4B4)
    override val accent: Color = Color(0xFF2A2A2A)
    override val accentForeground: Color = Color(0xFFEEEEEE)
    override val destructive: Color = Color(0xFFE54D2E)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFF201E18)
    override val input: Color = Color(0xFF484848)
    override val ring: Color = Color(0xFFFFE0C2)
    override val chart1: Color = Color(0xFFFFE0C2)
    override val chart2: Color = Color(0xFF393028)
    override val chart3: Color = Color(0xFF2A2A2A)
    override val chart4: Color = Color(0xFF42382E)
    override val chart5: Color = Color(0xFFFFE0C1)
    override val sidebar: Color = Color(0xFF18181B)
    override val sidebarForeground: Color = Color(0xFFF4F4F5)
    override val sidebarPrimary: Color = Color(0xFF1D4ED8)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFF27272A)
    override val sidebarAccentForeground: Color = Color(0xFFF4F4F5)
    override val sidebarBorder: Color = Color(0xFF27272A)
    override val sidebarRing: Color = Color(0xFFD4D4D8)
    override val snackbar: Color = Color(0xFF111111)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}