package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object Catppuccin : ShadcnStyles {
    override val background: Color = Color(0xFFEFF1F5)
    override val foreground: Color = Color(0xFF4C4F69)
    override val card: Color = Color(0xFFFFFFFF)
    override val cardForeground: Color = Color(0xFF4C4F69)
    override val popover: Color = Color(0xFFCCD0DA)
    override val popoverForeground: Color = Color(0xFF4C4F69)
    override val primary: Color = Color(0xFF8839EF)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFCCD0DA)
    override val secondaryForeground: Color = Color(0xFF4C4F69)
    override val muted: Color = Color(0xFFDCE0E8)
    override val mutedForeground: Color = Color(0xFF6C6F85)
    override val accent: Color = Color(0xFF04A5E5)
    override val accentForeground: Color = Color(0xFFFFFFFF)
    override val destructive: Color = Color(0xFFD20F39)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFBCC0CC)
    override val input: Color = Color(0xFFCCD0DA)
    override val ring: Color = Color(0xFF8839EF)
    override val chart1: Color = Color(0xFF8839EF)
    override val chart2: Color = Color(0xFF04A5E5)
    override val chart3: Color = Color(0xFF40A02B)
    override val chart4: Color = Color(0xFFFE640B)
    override val chart5: Color = Color(0xFFDC8A78)
    override val sidebar: Color = Color(0xFFE6E9EF)
    override val sidebarForeground: Color = Color(0xFF4C4F69)
    override val sidebarPrimary: Color = Color(0xFF8839EF)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFF04A5E5)
    override val sidebarAccentForeground: Color = Color(0xFFFFFFFF)
    override val sidebarBorder: Color = Color(0xFFBCC0CC)
    override val sidebarRing: Color = Color(0xFF8839EF)
    override val snackbar: Color = Color(0xFFEFF1F5)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object CatppuccinDark : ShadcnStyles {
    override val background: Color = Color(0xFF181825)
    override val foreground: Color = Color(0xFFCDD6F4)
    override val card: Color = Color(0xFF1E1E2E)
    override val cardForeground: Color = Color(0xFFCDD6F4)
    override val popover: Color = Color(0xFF45475A)
    override val popoverForeground: Color = Color(0xFFCDD6F4)
    override val primary: Color = Color(0xFFCBA6F7)
    override val primaryForeground: Color = Color(0xFF1E1E2E)
    override val secondary: Color = Color(0xFF585B70)
    override val secondaryForeground: Color = Color(0xFFCDD6F4)
    override val muted: Color = Color(0xFF292C3C)
    override val mutedForeground: Color = Color(0xFFA6ADC8)
    override val accent: Color = Color(0xFF89DCEB)
    override val accentForeground: Color = Color(0xFF1E1E2E)
    override val destructive: Color = Color(0xFFF38BA8)
    override val destructiveForeground: Color = Color(0xFF1E1E2E)
    override val border: Color = Color(0xFF313244)
    override val input: Color = Color(0xFF313244)
    override val ring: Color = Color(0xFFCBA6F7)
    override val chart1: Color = Color(0xFFCBA6F7)
    override val chart2: Color = Color(0xFF89DCEB)
    override val chart3: Color = Color(0xFFA6E3A1)
    override val chart4: Color = Color(0xFFFAB387)
    override val chart5: Color = Color(0xFFF5E0DC)
    override val sidebar: Color = Color(0xFF11111B)
    override val sidebarForeground: Color = Color(0xFFCDD6F4)
    override val sidebarPrimary: Color = Color(0xFFCBA6F7)
    override val sidebarPrimaryForeground: Color = Color(0xFF1E1E2E)
    override val sidebarAccent: Color = Color(0xFF89DCEB)
    override val sidebarAccentForeground: Color = Color(0xFF1E1E2E)
    override val sidebarBorder: Color = Color(0xFF45475A)
    override val sidebarRing: Color = Color(0xFFCBA6F7)
    override val snackbar: Color = Color(0xFF181825)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}