package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object Claude : ShadcnStyles {
    override val background: Color = Color(0xFFFAF9F5)
    override val foreground: Color = Color(0xFF3D3929)
    override val card: Color = Color(0xFFFAF9F5)
    override val cardForeground: Color = Color(0xFF141413)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF28261B)
    override val primary: Color = Color(0xFFC96442)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFE9E6DC)
    override val secondaryForeground: Color = Color(0xFF535146)
    override val muted: Color = Color(0xFFEDE9DE)
    override val mutedForeground: Color = Color(0xFF83827D)
    override val accent: Color = Color(0xFFE9E6DC)
    override val accentForeground: Color = Color(0xFF28261B)
    override val destructive: Color = Color(0xFF141413)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFDAD9D4)
    override val input: Color = Color(0xFFB4B2A7)
    override val ring: Color = Color(0xFFC96442)
    override val chart1: Color = Color(0xFFB05730)
    override val chart2: Color = Color(0xFF9C87F5)
    override val chart3: Color = Color(0xFFDED8C4)
    override val chart4: Color = Color(0xFFDBD3F0)
    override val chart5: Color = Color(0xFFB4552D)
    override val sidebar: Color = Color(0xFFF5F4EE)
    override val sidebarForeground: Color = Color(0xFF3D3D3A)
    override val sidebarPrimary: Color = Color(0xFFC96442)
    override val sidebarPrimaryForeground: Color = Color(0xFFFBFBFB)
    override val sidebarAccent: Color = Color(0xFFE9E6DC)
    override val sidebarAccentForeground: Color = Color(0xFF343434)
    override val sidebarBorder: Color = Color(0xFFEBEBEB)
    override val sidebarRing: Color = Color(0xFFB5B5B5)
    override val snackbar: Color = Color(0xFFFAF9F5)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object ClaudeDark : ShadcnStyles {
    override val background: Color = Color(0xFF262624)
    override val foreground: Color = Color(0xFFC3C0B6)
    override val card: Color = Color(0xFF262624)
    override val cardForeground: Color = Color(0xFFFAF9F5)
    override val popover: Color = Color(0xFF30302E)
    override val popoverForeground: Color = Color(0xFFE5E5E2)
    override val primary: Color = Color(0xFFD97757)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFFAF9F5)
    override val secondaryForeground: Color = Color(0xFF30302E)
    override val muted: Color = Color(0xFF1B1B19)
    override val mutedForeground: Color = Color(0xFFB7B5A9)
    override val accent: Color = Color(0xFF1A1915)
    override val accentForeground: Color = Color(0xFFF5F4EE)
    override val destructive: Color = Color(0xFFEF4444)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFF3E3E38)
    override val input: Color = Color(0xFF52514A)
    override val ring: Color = Color(0xFFD97757)
    override val chart1: Color = Color(0xFFB05730)
    override val chart2: Color = Color(0xFF9C87F5)
    override val chart3: Color = Color(0xFF1A1915)
    override val chart4: Color = Color(0xFF2F2B48)
    override val chart5: Color = Color(0xFFB4552D)
    override val sidebar: Color = Color(0xFF1F1E1D)
    override val sidebarForeground: Color = Color(0xFFC3C0B6)
    override val sidebarPrimary: Color = Color(0xFF343434)
    override val sidebarPrimaryForeground: Color = Color(0xFFFBFBFB)
    override val sidebarAccent: Color = Color(0xFF0F0F0E)
    override val sidebarAccentForeground: Color = Color(0xFFC3C0B6)
    override val sidebarBorder: Color = Color(0xFFEBEBEB)
    override val sidebarRing: Color = Color(0xFFB5B5B5)
    override val snackbar: Color = Color(0xFF262624)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 3.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}