package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object NeoBrutalism : ShadcnStyles {
    override val background: Color = Color(0xFFFFFFFF)
    override val foreground: Color = Color(0xFF000000)
    override val card: Color = Color(0xFFFFFFFF)
    override val cardForeground: Color = Color(0xFF000000)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF000000)
    override val primary: Color = Color(0xFFFF3333)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFFFFF00)
    override val secondaryForeground: Color = Color(0xFF000000)
    override val muted: Color = Color(0xFFF0F0F0)
    override val mutedForeground: Color = Color(0xFF333333)
    override val accent: Color = Color(0xFF0066FF)
    override val accentForeground: Color = Color(0xFFFFFFFF)
    override val destructive: Color = Color(0xFF000000)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFF000000)
    override val input: Color = Color(0xFF000000)
    override val ring: Color = Color(0xFFFF3333)
    override val chart1: Color = Color(0xFFFF3333)
    override val chart2: Color = Color(0xFFFFFF00)
    override val chart3: Color = Color(0xFF0066FF)
    override val chart4: Color = Color(0xFF00CC00)
    override val chart5: Color = Color(0xFFCC00CC)
    override val sidebar: Color = Color(0xFFF0F0F0)
    override val sidebarForeground: Color = Color(0xFF000000)
    override val sidebarPrimary: Color = Color(0xFFFF3333)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFF0066FF)
    override val sidebarAccentForeground: Color = Color(0xFFFFFFFF)
    override val sidebarBorder: Color = Color(0xFF000000)
    override val sidebarRing: Color = Color(0xFFFF3333)
    override val snackbar: Color = Color(0xFFFFFFFF)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 6.dp,
            offsetY = 6.dp,
            blurRadius = 0.dp,
            spread = 3.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 6.dp,
            offsetY = 6.dp,
            blurRadius = 0.dp,
            spread = 3.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 4.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 10.dp,
            offsetY = 10.dp,
            blurRadius = 0.dp,
            spread = 6.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 10.dp,
            offsetY = 10.dp,
            blurRadius = 0.dp,
            spread = 8.dp,
            color = MaterialTheme.styles.border
        )
    )
}

object NeoBrutalismDark : ShadcnStyles {
    override val background: Color = Color(0xFF000000)
    override val foreground: Color = Color(0xFFFFFFFF)
    override val card: Color = Color(0xFF333333)
    override val cardForeground: Color = Color(0xFFFFFFFF)
    override val popover: Color = Color(0xFF333333)
    override val popoverForeground: Color = Color(0xFFFFFFFF)
    override val primary: Color = Color(0xFFFF6666)
    override val primaryForeground: Color = Color(0xFF000000)
    override val secondary: Color = Color(0xFFFFFF33)
    override val secondaryForeground: Color = Color(0xFF000000)
    override val muted: Color = Color(0xFF1A1A1A)
    override val mutedForeground: Color = Color(0xFFCCCCCC)
    override val accent: Color = Color(0xFF3399FF)
    override val accentForeground: Color = Color(0xFF000000)
    override val destructive: Color = Color(0xFFFFFFFF)
    override val destructiveForeground: Color = Color(0xFF000000)
    override val border: Color = Color(0xFFFFFFFF)
    override val input: Color = Color(0xFFFFFFFF)
    override val ring: Color = Color(0xFFFF6666)
    override val chart1: Color = Color(0xFFFF6666)
    override val chart2: Color = Color(0xFFFFFF33)
    override val chart3: Color = Color(0xFF3399FF)
    override val chart4: Color = Color(0xFF33CC33)
    override val chart5: Color = Color(0xFFCC33CC)
    override val sidebar: Color = Color(0xFF000000)
    override val sidebarForeground: Color = Color(0xFFFFFFFF)
    override val sidebarPrimary: Color = Color(0xFFFF6666)
    override val sidebarPrimaryForeground: Color = Color(0xFF000000)
    override val sidebarAccent: Color = Color(0xFF3399FF)
    override val sidebarAccentForeground: Color = Color(0xFF000000)
    override val sidebarBorder: Color = Color(0xFFFFFFFF)
    override val sidebarRing: Color = Color(0xFFFF6666)
    override val snackbar: Color = Color(0xFF000000)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 4.dp,
            offsetY = 4.dp,
            blurRadius = 0.dp,
            spread = 0.dp,
            color = MaterialTheme.styles.border
        )
    )
}