package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object OceanBreeze : ShadcnStyles {
    override val background: Color = Color(0xFFF0F8FF)
    override val foreground: Color = Color(0xFF374151)
    override val card: Color = Color(0xFFFFFFFF)
    override val cardForeground: Color = Color(0xFF374151)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF374151)
    override val primary: Color = Color(0xFF22C55E)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFE0F2FE)
    override val secondaryForeground: Color = Color(0xFF4B5563)
    override val muted: Color = Color(0xFFF3F4F6)
    override val mutedForeground: Color = Color(0xFF6B7280)
    override val accent: Color = Color(0xFFD1FAE5)
    override val accentForeground: Color = Color(0xFF374151)
    override val destructive: Color = Color(0xFFEF4444)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFE5E7EB)
    override val input: Color = Color(0xFFE5E7EB)
    override val ring: Color = Color(0xFF22C55E)
    override val chart1: Color = Color(0xFF22C55E)
    override val chart2: Color = Color(0xFF10B981)
    override val chart3: Color = Color(0xFF059669)
    override val chart4: Color = Color(0xFF047857)
    override val chart5: Color = Color(0xFF065F46)
    override val sidebar: Color = Color(0xFFE0F2FE)
    override val sidebarForeground: Color = Color(0xFF374151)
    override val sidebarPrimary: Color = Color(0xFF22C55E)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFFD1FAE5)
    override val sidebarAccentForeground: Color = Color(0xFF374151)
    override val sidebarBorder: Color = Color(0xFFE5E7EB)
    override val sidebarRing: Color = Color(0xFF22C55E)
    override val snackbar: Color = Color(0xFFF0F8FF)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
}

object OceanBreezeDark : ShadcnStyles {
    override val background: Color = Color(0xFF0F172A)
    override val foreground: Color = Color(0xFFD1D5DB)
    override val card: Color = Color(0xFF1E293B)
    override val cardForeground: Color = Color(0xFFD1D5DB)
    override val popover: Color = Color(0xFF1E293B)
    override val popoverForeground: Color = Color(0xFFD1D5DB)
    override val primary: Color = Color(0xFF34D399)
    override val primaryForeground: Color = Color(0xFF0F172A)
    override val secondary: Color = Color(0xFF2D3748)
    override val secondaryForeground: Color = Color(0xFFA1A1AA)
    override val muted: Color = Color(0xFF19212E)
    override val mutedForeground: Color = Color(0xFF6B7280)
    override val accent: Color = Color(0xFF374151)
    override val accentForeground: Color = Color(0xFFA1A1AA)
    override val destructive: Color = Color(0xFFEF4444)
    override val destructiveForeground: Color = Color(0xFF0F172A)
    override val border: Color = Color(0xFF4B5563)
    override val input: Color = Color(0xFF4B5563)
    override val ring: Color = Color(0xFF34D399)
    override val chart1: Color = Color(0xFF34D399)
    override val chart2: Color = Color(0xFF2DD4BF)
    override val chart3: Color = Color(0xFF22C55E)
    override val chart4: Color = Color(0xFF10B981)
    override val chart5: Color = Color(0xFF059669)
    override val sidebar: Color = Color(0xFF1E293B)
    override val sidebarForeground: Color = Color(0xFFD1D5DB)
    override val sidebarPrimary: Color = Color(0xFF34D399)
    override val sidebarPrimaryForeground: Color = Color(0xFF0F172A)
    override val sidebarAccent: Color = Color(0xFF374151)
    override val sidebarAccentForeground: Color = Color(0xFFA1A1AA)
    override val sidebarBorder: Color = Color(0xFF4B5563)
    override val sidebarRing: Color = Color(0xFF34D399)
    override val snackbar: Color = Color(0xFF0F172A)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-2).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 8.dp,
            spread = (-1).dp,
            color = MaterialTheme.styles.border
        )
    )
}