package dr.shadcn.kmp.themes.styles

// Generated by tailwindToKotlin
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.shadcn.ui.themes.BoxShadow
import com.shadcn.ui.themes.ShadcnStyles
import com.shadcn.ui.themes.styles

// NOTE: This file assumes the interface ShadcnStyles and BoxShadow class are declared elsewhere.
object PastelDreams : ShadcnStyles {
    override val background: Color = Color(0xFFF7F3F9)
    override val foreground: Color = Color(0xFF374151)
    override val card: Color = Color(0xFFFFFFFF)
    override val cardForeground: Color = Color(0xFF374151)
    override val popover: Color = Color(0xFFFFFFFF)
    override val popoverForeground: Color = Color(0xFF374151)
    override val primary: Color = Color(0xFFA78BFA)
    override val primaryForeground: Color = Color(0xFFFFFFFF)
    override val secondary: Color = Color(0xFFE9D8FD)
    override val secondaryForeground: Color = Color(0xFF4B5563)
    override val muted: Color = Color(0xFFF3E8FF)
    override val mutedForeground: Color = Color(0xFF6B7280)
    override val accent: Color = Color(0xFFF3E5F5)
    override val accentForeground: Color = Color(0xFF374151)
    override val destructive: Color = Color(0xFFFCA5A5)
    override val destructiveForeground: Color = Color(0xFFFFFFFF)
    override val border: Color = Color(0xFFE9D8FD)
    override val input: Color = Color(0xFFE9D8FD)
    override val ring: Color = Color(0xFFA78BFA)
    override val chart1: Color = Color(0xFFA78BFA)
    override val chart2: Color = Color(0xFF8B5CF6)
    override val chart3: Color = Color(0xFF7C3AED)
    override val chart4: Color = Color(0xFF6D28D9)
    override val chart5: Color = Color(0xFF5B21B6)
    override val sidebar: Color = Color(0xFFE9D8FD)
    override val sidebarForeground: Color = Color(0xFF374151)
    override val sidebarPrimary: Color = Color(0xFFA78BFA)
    override val sidebarPrimaryForeground: Color = Color(0xFFFFFFFF)
    override val sidebarAccent: Color = Color(0xFFF3E5F5)
    override val sidebarAccentForeground: Color = Color(0xFF374151)
    override val sidebarBorder: Color = Color(0xFFE9D8FD)
    override val sidebarRing: Color = Color(0xFFA78BFA)
    override val snackbar: Color = Color(0xFFF7F3F9)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
}

object PastelDreamsDark : ShadcnStyles {
    override val background: Color = Color(0xFF1C1917)
    override val foreground: Color = Color(0xFFE0E7FF)
    override val card: Color = Color(0xFF2D2535)
    override val cardForeground: Color = Color(0xFFE0E7FF)
    override val popover: Color = Color(0xFF2D2535)
    override val popoverForeground: Color = Color(0xFFE0E7FF)
    override val primary: Color = Color(0xFFC0AAFD)
    override val primaryForeground: Color = Color(0xFF1C1917)
    override val secondary: Color = Color(0xFF3F324A)
    override val secondaryForeground: Color = Color(0xFFD1D5DB)
    override val muted: Color = Color(0xFF20182B)
    override val mutedForeground: Color = Color(0xFF9CA3AF)
    override val accent: Color = Color(0xFF4A3D5A)
    override val accentForeground: Color = Color(0xFFD1D5DB)
    override val destructive: Color = Color(0xFFFCA5A5)
    override val destructiveForeground: Color = Color(0xFF1C1917)
    override val border: Color = Color(0xFF3F324A)
    override val input: Color = Color(0xFF3F324A)
    override val ring: Color = Color(0xFFC0AAFD)
    override val chart1: Color = Color(0xFFC0AAFD)
    override val chart2: Color = Color(0xFFA78BFA)
    override val chart3: Color = Color(0xFF8B5CF6)
    override val chart4: Color = Color(0xFF7C3AED)
    override val chart5: Color = Color(0xFF6D28D9)
    override val sidebar: Color = Color(0xFF3F324A)
    override val sidebarForeground: Color = Color(0xFFE0E7FF)
    override val sidebarPrimary: Color = Color(0xFFC0AAFD)
    override val sidebarPrimaryForeground: Color = Color(0xFF1C1917)
    override val sidebarAccent: Color = Color(0xFF4A3D5A)
    override val sidebarAccentForeground: Color = Color(0xFFD1D5DB)
    override val sidebarBorder: Color = Color(0xFF3F324A)
    override val sidebarRing: Color = Color(0xFFC0AAFD)
    override val snackbar: Color = Color(0xFF1C1917)
    @Composable
    override fun shadow2xs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXs(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowSm(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 1.dp,
            blurRadius = 2.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowMd(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 2.dp,
            blurRadius = 4.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowLg(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 4.dp,
            blurRadius = 6.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadowXl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        ),
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 10.dp,
            spread = (-5).dp,
            color = MaterialTheme.styles.border
        )
    )
    @Composable
    override fun shadow2xl(): List<BoxShadow> = listOf(
        BoxShadow(
            offsetX = 0.dp,
            offsetY = 8.dp,
            blurRadius = 16.dp,
            spread = (-4).dp,
            color = MaterialTheme.styles.border
        )
    )
}